# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.sort_field import SortField


class TestSortField(unittest.TestCase):
    """ SortField unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortField(self):
        """
        Test SortField
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.sort_field.SortField()
        pass


if __name__ == '__main__':
    unittest.main()
