# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.geo_area import GeoArea


class TestGeoArea(unittest.TestCase):
    """ GeoArea unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoArea(self):
        """
        Test GeoArea
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.geo_area.GeoArea()
        pass


if __name__ == '__main__':
    unittest.main()
