# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.metadata_api import MetadataApi


class TestMetadataApi(unittest.TestCase):
    """ MetadataApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.metadata_api.MetadataApi()

    def tearDown(self):
        pass

    def test_get_allowed_date_formats(self):
        """
        Test case for get_allowed_date_formats

        
        """
        pass

    def test_get_controlled_list_phase_or_stage(self):
        """
        Test case for get_controlled_list_phase_or_stage

        
        """
        pass

    def test_get_controlled_list_sex(self):
        """
        Test case for get_controlled_list_sex

        
        """
        pass

    def test_get_controlled_list_specimen_type_status(self):
        """
        Test case for get_controlled_list_specimen_type_status

        
        """
        pass

    def test_get_controlled_list_taxonomic_status(self):
        """
        Test case for get_controlled_list_taxonomic_status

        
        """
        pass

    def test_get_controlled_lists(self):
        """
        Test case for get_controlled_lists

        
        """
        pass

    def test_get_rest_services(self):
        """
        Test case for get_rest_services

        
        """
        pass

    def test_get_setting(self):
        """
        Test case for get_setting

        
        """
        pass

    def test_get_settings(self):
        """
        Test case for get_settings

        
        """
        pass

    def test_get_source_systems(self):
        """
        Test case for get_source_systems

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
