# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.summary_source_system import SummarySourceSystem


class TestSummarySourceSystem(unittest.TestCase):
    """ SummarySourceSystem unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSummarySourceSystem(self):
        """
        Test SummarySourceSystem
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.summary_source_system.SummarySourceSystem()
        pass


if __name__ == '__main__':
    unittest.main()
