# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.source_system import SourceSystem


class TestSourceSystem(unittest.TestCase):
    """ SourceSystem unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceSystem(self):
        """
        Test SourceSystem
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.source_system.SourceSystem()
        pass


if __name__ == '__main__':
    unittest.main()
