# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.specimen import Specimen


class TestSpecimen(unittest.TestCase):
    """ Specimen unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecimen(self):
        """
        Test Specimen
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.specimen.Specimen()
        pass


if __name__ == '__main__':
    unittest.main()
