# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Monomial(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rank': 'str',
        'name': 'str'
    }

    attribute_map = {
        'rank': 'rank',
        'name': 'name'
    }

    def __init__(self, rank=None, name=None):
        """
        Monomial - a model defined in Swagger
        """

        self._rank = None
        self._name = None
        self.discriminator = None

        if rank is not None:
          self.rank = rank
        if name is not None:
          self.name = name

    @property
    def rank(self):
        """
        Gets the rank of this Monomial.

        :return: The rank of this Monomial.
        :rtype: str
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """
        Sets the rank of this Monomial.

        :param rank: The rank of this Monomial.
        :type: str
        """

        self._rank = rank

    @property
    def name(self):
        """
        Gets the name of this Monomial.

        :return: The name of this Monomial.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Monomial.

        :param name: The name of this Monomial.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Monomial):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
