# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SortField(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'Path',
        'sort_order': 'str',
        'ascending': 'bool'
    }

    attribute_map = {
        'path': 'path',
        'sort_order': 'sortOrder',
        'ascending': 'ascending'
    }

    def __init__(self, path=None, sort_order=None, ascending=None):
        """
        SortField - a model defined in Swagger
        """

        self._path = None
        self._sort_order = None
        self._ascending = None
        self.discriminator = None

        if path is not None:
          self.path = path
        if sort_order is not None:
          self.sort_order = sort_order
        if ascending is not None:
          self.ascending = ascending

    @property
    def path(self):
        """
        Gets the path of this SortField.

        :return: The path of this SortField.
        :rtype: Path
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this SortField.

        :param path: The path of this SortField.
        :type: Path
        """

        self._path = path

    @property
    def sort_order(self):
        """
        Gets the sort_order of this SortField.

        :return: The sort_order of this SortField.
        :rtype: str
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """
        Sets the sort_order of this SortField.

        :param sort_order: The sort_order of this SortField.
        :type: str
        """
        allowed_values = ["ASC", "DESC"]
        if sort_order not in allowed_values:
            raise ValueError(
                "Invalid value for `sort_order` ({0}), must be one of {1}"
                .format(sort_order, allowed_values)
            )

        self._sort_order = sort_order

    @property
    def ascending(self):
        """
        Gets the ascending of this SortField.

        :return: The ascending of this SortField.
        :rtype: bool
        """
        return self._ascending

    @ascending.setter
    def ascending(self, ascending):
        """
        Sets the ascending of this SortField.

        :param ascending: The ascending of this SortField.
        :type: bool
        """

        self._ascending = ascending

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SortField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
